### ISSUE TITLE
Include a history of the restaurant

### ISSUE THREAD

**Issue by jennypenfield** [jennypenfield/restaurant-group-project#14]
Andrew, I know you will love doing this one!
Ci! -A

**Comment by agrahamt** [comment]
Okay, maybe Lorem Ipsum is better, but I gave it a shot.
This derives from having worked with Art History professors for seven years.
_Subedei_ is on the cutting edge of historically-accurate world adventure cuisine. Let us show you the hospitality of the Great Khans!
Chef and founder **Dr. Jacques Temuchin** (PhD. History, University of Texas, [CV](url)) is one of the leaders of the Historical gastronomy movement.  A dashing explorer flluent in Uyghur, Jurchen, Medieval Russian, and Arabic languages, Temuchin is an expert in reconstructing medieval recipes with scrupulous attention to detail, and served as head sous chef at Medieval Times, Austin for two years.  

“Dr. Jack” is also a captivating lecturer available for two-hour history slideshow/dinner/drinking parties upon request.

**Comment by jennypenfield** [comment]
Are we calling it Medieval Times or Mongolian Fusion? This seems like more of an "About the Restaurant" rather than a history. I think we can combine them into a history/about section, though. 

Can you start off by saying how and when the restaurant started? 

What is the 'historical gastronomy movement'? Are you referring to [this](http://www.culinaryschools.com/what-is-molecular-gastronomy-definition) ? 

If so, can you say "molecular gastronomy" and include a little explanation for the rest of us...? :)

Also, it might be good to include a contact link or a "more information" to reserve Dr. Jack for the two-hour parties.

**Comment by agrahamt** [comment]
I made up the historical gatronomy movement, though obviously things like that will exist.  Historical means historical, gastronomy just means "foody stuff".  Put it together, and you've got a fake movement (although admittedly it probably exists, though I haven't Googled it).

It is just supposed to sound self-important.

_Medieval Times_ is an existing theme restaurant that is pretty cheesy, so it was a specific reference.  Here's their website, I have no idea if there is one in Austin.  
Dorky website:  http://www.medievaltimes.com/plan-your-trip/dallas-tx/index.html
We could just as easily do a Klingon-themed restaurant with Klingon-style fair, or Tolkien-elf restaurant.  Just a typical weird-theme idea blown out of proportion.

The counter-narrative (aka the real story) was the chef is primarily an academic masquerading as a chef with his PhD from UTAustin but little cooking credentials (sous chef at cheesy renaissance fair restaurant).  Maybe he couldn't get a teaching gig.
We can always toss the whole concept.  Temuchin is also Genghis Khan's real name.  
My thought was that the lecture dinners sounded like torture, not fun, although I admit that maybe they could be fun with sufficient lighter fluid.

**Comment by agrahamt** [comment]
Here you go - "[historical gastronomy](https://books.google.com/books?id=3ilvBQAAQBAJ&pg=PT330&lpg=PT330&dq=%22historical+gastronomy%22&source=bl&ots=dcaBJ9d-2F&sig=N6xSrAqytJtczjRBDZVd3--d_PA&hl=en&sa=X&ved=0ahUKEwiCo_Cgp67TAhVqxVQKHfLpAH8Q6AEIWTAO#v=onepage&q=%22historical%20gastronomy%22&f=false)" - it had to exist!
This is the kind of stuff I was thinking about.

**Comment by jennypenfield** [comment]
Closed with PR #36
